trigger: none

pool:
  name: Sandeeplocal

steps:

- task: AzureCLI@2
  displayName: "Create Resource Group"
  inputs:
    azureSubscription: '797af31e-8795-4440-b043-eb9d24842511'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create `
        --name rg-pipeline-demo `
        --location westeurope
